services:
  tilbakemeldingsmottak-oauth2-server:
    hostname: tilbakemeldingsmottak-oauth2-server
    image: ghcr.io/navikt/mock-oauth2-server:0.5.8
    ports:
      - 9068:9068
    environment:
      - SERVER_PORT=9068