services:
  tilbakemeldingsmottak-oauth2-server:
    hostname: tilbakemeldingsmottak-oauth2-server
    image: ghcr.io/navikt/mock-oauth2-server:0.5.8
    ports:
      - 9068:9068
    environment:
      - SERVER_PORT=9068
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5430:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local