kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: tilbakemeldingsmottak
  namespace: {{ NAMESPACE }}
  labels:
    team: teamserviceklage
spec:
  env:
  - name: SPRING_DATASOURCE_URL
    value: {{ SPRING_DATASOURCE_URL }}
  - name: AZUREAD_CLIENTID
    value: {{ AZUREAD_CLIENTID }}
  - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
    value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
  - name: SECURITYTOKENSERVICE_URL
    value: {{ SECURITYTOKENSERVICE_URL }}
  - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREAD_DISCOVERYURL
    value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREAD_DISCOVERYURL }}
  - name: LOGINSERVICE_ACCEPTED_AUDIENCE
    value: {{ LOGINSERVICE_ACCEPTED_AUDIENCE }}
  - name: LOGINSERVICE_OIDC_CALLBACKURI
    value: {{ LOGINSERVICE_OIDC_CALLBACKURI }}
  - name: NO_NAV_SECURITY_JWT_ISSUER_ISSO_DISCOVERYURL
    value: {{ NO_NAV_SECURITY_JWT_ISSUER_ISSO_DISCOVERYURL }}
  - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
    value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
  - name: JOURNALPOST_V1_URL
    value: {{ JOURNALPOST_V1_URL }}
  - name: OPPGAVE_OPPGAVER_URL
    value: {{ OPPGAVE_OPPGAVER_URL }}
  - name: AKTOERREGISTER_IDENTER_URL
    value: {{ AKTOERREGISTER_IDENTER_URL }}
  - name: EREG_API_URL
    value: {{ EREG_API_URL }}
  - name: NORG2_API_V1_URL
    value: {{ NORG2_API_V1_URL }}
  - name: LOGINSERVICE_URL
    value: {{ LOGINSERVICE_URL }}
  image: {{ image }}
  ingresses:
  - {{ INGRESS }}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
    - kvPath: {{ DB_PATH }}
      mountPath: /var/run/secrets/nais.io/tilbakemeldingsmottak
    - kvPath: {{ SRVUSER_PATH }}
      mountPath: /var/run/secrets/nais.io/srvtilbakemeldingsmottak
    - kvPath: {{ SECRETS_PATH }}
      mountPath: /var/run/secrets/nais.io/vault
