package no.nav.tilbakemeldingsmottak.domain


object ServiceklageConstants {
    const val SERVICEKLAGE_ID = "SERVICEKLAGE_ID"
    const val JOURNALPOST_ID = "JOURNALPOST_ID"
    const val OPPRETTET_DATO = "OPPRETTET_DATO"
    const val KLAGEN_GJELDER_ID = "KLAGEN_GJELDER_ID"
    const val INNLOGGET = "INNLOGGET"
    const val KLAGETYPER = "KLAGETYPER"
    const val KLAGETYPE_UTDYPNING = "KLAGETYPE_UTDYPNING"
    const val GJELDER_SOSIALHJELP = "GJELDER_SOSIALHJELP"
    const val KLAGETEKST = "KLAGETEKST"
    const val BEHANDLES_SOM_SERVICEKLAGE = "BEHANDLES_SOM_SERVICEKLAGE"
    const val FREMMET_DATO = "FREMMET_DATO"
    const val INNSENDER = "INNSENDER"
    const val KANAL = "KANAL"
    const val PAAKLAGET_ENHET_ER_BEHANDLENDE = "PAAKLAGET_ENHET_ER_BEHANDLENDE"
    const val ENHETSNUMMER_PAAKLAGET = "ENHETSNUMMER_PAAKLAGET"
    const val ENHETSNUMMER_BEHANDLENDE = "ENHETSNUMMER_BEHANDLENDE"
    const val GJELDER = "GJELDER"
    const val YTELSE = "YTELSE"
    const val TEMA = "TEMA"
    const val RELATERT = "RELATERT"
    const val VENTE = "VENTE"
    const val TILGJENGELIGHET = "TILGJENGELIGHET"
    const val INFORMASJON = "INFORMASJON"
    const val VEILEDNING = "VEILEDNING"
    const val UTFALL = "UTFALL"
    const val AARSAK = "AARSAK"
    const val TILTAK = "TILTAK"
    const val SVARMETODE = "SVARMETODE"
    const val SVAR_IKKE_NOEDVENDIG = "SVAR_IKKE_NOEDVENDIG"
    const val BEHANDLES_SOM_SERVICEKLAGE_UTDYPNING = "BEHANDLES_SOM_SERVICEKLAGE_UTDYPNING"
    const val FULGT_BRUKERVEILEDNING_GOSYS = "FULGT_BRUKERVEILEDNING_GOSYS"
    const val KOMMUNAL_BEHANDLING = "KOMMUNAL_BEHANDLING"
    const val KANAL_UTDYPNING = "KANAL_UTDYPNING"
    const val BESKRIVELSE = "BESKRIVELSE"
    const val TEMA_UTDYPNING = "TEMA_UTDYPNING"
    const val SVARMETODE_UTDYPNING = "SVARMETODE_UTDYPNING"
    const val KVITTERING = "KVITTERING"
    const val AVSLUTTET_DATO = "AVSLUTTET_DATO"
    const val KLASSIFISERING_JSON = "KLASSIFISERING_JSON"
    const val SKJEMA_VERSJON = "SKJEMA_VERSJON"
    const val SVAR_IKKE_NOEDVENDIG_ANSWER = "Svar ikke nødvendig"
    const val BRUKER_IKKE_BEDT_OM_SVAR_ANSWER = "Bruker ikke bedt om svar"
    const val INNMELDER_MANGLER_FULLMAKT_ANSWER = "Innmelder har ikke fullmakt på vegne av bruker"
    const val KANAL_SERVICEKLAGESKJEMA_ANSWER = "Serviceklageskjema på nav.no"
    const val KANAL_MUNTLIG_ANSWER = "Muntlig fra bruker"
    const val NONE = "none"

    const val KOMMUNAL_KLAGE = "Nei, serviceklagen gjelder kommunale tjenester eller ytelser"
    const val FORVALTNINGSKLAGE = "Nei, en forvaltningsklage"
    const val SKRIV_TIL_OSS = "Nei, Skriv til oss"
    const val JA = "Ja"
    const val ANNET = "Annet"
}
