CREATE TABLE serviceklage (
  SERVICEKLAGE_ID                   INTEGER,
  JOURNALPOST_ID                    VARCHAR(10) NOT NULL,
  OPPRETTET_DATO                    TIMESTAMP(6) NOT NULL,
  KLAGEN_GJELDER_ID                 VARCHAR(15),
  KLAGETYPE                         VARCHAR(100),
  KLAGETEKST                        TEXT,
  BEHANDLES_SOM_SERVICEKLAGE        VARCHAR(100),
  FREMMET_DATO                      TIMESTAMP(6),
  INNSENDER                         VARCHAR(100),
  KANAL                             VARCHAR(100),
  ENHETSNUMMER_PAAKLAGET            VARCHAR(4),
  ENHETSNUMMER_BEHANDLENDE          VARCHAR(4),
  GJELDER                           VARCHAR(100),
  YTELSE                            VARCHAR(100),
  TEMA                              VARCHAR(100),
  VEILEDNING                        VARCHAR(100),
  UTFALL                            VARCHAR(100),
  SVARMETODE                        VARCHAR(100),
  SVAR_IKKE_NOEDVENDIG              VARCHAR(100),
  SCHEMA_VERSION                    INTEGER,
  KLASSIFISERING_JSON               TEXT,
  PRIMARY KEY (serviceklage_id)
);
CREATE SEQUENCE serviceklage_serviceklage_id_seq;