CREATE TABLE serviceklage (
  SERVICEKLAGE_ID                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  JOURNALPOST_ID                    VARCHAR2(11) NOT NULL,
  OPPRETTET_DATO                    TIMESTAMP NOT NULL,
  KLAGEN_GJELDER_ID                 VARCHAR2(15),
  KLAGETYPE                         VARCHAR2(100),
  KLAGETEKST                        CLOB,
  BEHANDLES_SOM_SERVICEKLAGE        VARCHAR2(100),
  FREMMET_DATO                      TIMESTAMP,
  INNSENDER                         VARCHAR2(100),
  KANAL                             VARCHAR2(100),
  ENHETSNUMMER_PAAKLAGET            VARCHAR2(4),
  ENHETSNUMMER_BEHANDLENDE          VARCHAR2(4),
  GJELDER                           VARCHAR2(100),
  YTELSE                            VARCHAR2(100),
  TEMA                              VARCHAR2(100),
  VEILEDNING                        VARCHAR2(100),
  UTFALL                            VARCHAR2(100),
  SVARMETODE                        VARCHAR2(100),
  SVAR_IKKE_NOEDVENDIG              VARCHAR2(100),
  SCHEMA_VERSION                    NUMBER,
  KLASSIFISERING_JSON               CLOB
);