CREATE TABLE serviceklage (
  SERVICEKLAGE_ID                             SERIAL PRIMARY KEY,
  JOURNALPOST_ID                              VARCHAR(11),
  OPPRETTET_DATO                              TIMESTAMP NOT NULL,
  KLAGEN_GJELDER_ID                           VARCHAR(15),
  KLAGETYPER                                  VARCHAR(200),
  GJELDER_SOSIALHJELP                         VARCHAR(100),
  KLAGETEKST                                  TEXT,
  BEHANDLES_SOM_SERVICEKLAGE                  VARCHAR(100),
  BEHANDLES_SOM_SERVICEKLAGE_UTDYPNING        VARCHAR(2000),
  FREMMET_DATO                                TIMESTAMP,
  INNSENDER                                   VARCHAR(100),
  KANAL                                       VARCHAR(100),
  KANAL_UTDYPNING                             VARCHAR(2000),
  ENHETSNUMMER_PAAKLAGET                      VARCHAR(4),
  ENHETSNUMMER_BEHANDLENDE                    VARCHAR(4),
  GJELDER                                     VARCHAR(100),
  BESKRIVELSE                                 TEXT,
  YTELSE                                      VARCHAR(100),
  TEMA                                        VARCHAR(100),
  TEMA_UTDYPNING                              VARCHAR(2000),
  VEILEDNING                                  VARCHAR(100),
  UTFALL                                      VARCHAR(100),
  AARSAK                                      VARCHAR(2000),
  TILTAK                                      VARCHAR(2000),
  SVARMETODE                                  VARCHAR(100),
  SVARMETODE_UTDYPNING                        VARCHAR(2000),
  AVSLUTTET_DATO                              TIMESTAMP,
  SKJEMA_VERSJON                              INTEGER,
  KLASSIFISERING_JSON                         TEXT
);