version: '1'

questions:
- id: BEHANDLES_SOM_SERVICEKLAGE
  type: RADIO
  answers:
  - answer: Ja
  - answer: Ja, men inneholder også andre elementer
    questions:
    - id: BEHANDLES_SOM_SERVICEKLAGE_SPESIFISER
      type: TEXT
  - answer: Nei, innsender har ikke fullmakt på vegne av bruker
    emit: Du må skrive til innsender at serviceklagen ikke kan besvares fordi fullmakt mangler
    next: none
  - answer: Nei, serviceklagen gjelder kommunale tjenester eller ytelser
    emit: Serviceklagen kan ikke behandles i denne løsningen. Overfør til kommunalt NAV kontor.(se rutine)
    next: none
  - answer: Nei - en forvaltningsklage
    emit: Du må endre journalføringen og sørge for at riktig instans får forvaltningsklagen til behandling.
    next: none
  - answer: Nei - en beskjed til NAV
    emit: Du må endre journalføringen og sørge for at riktig instans får dokumentet til behandling.
    next: none
  - answer: Nei - annet
    questions:
    - id: BEHANDLES_SOM_SERVICEKLAGE_SPESIFISER
      type: TEXT
    next: none

- id: FREMMET_DATO
  type: DATE

- id: INNSENDER
  type: RADIO
  answers:
  - answer: Bruker selv som privatperson
  - answer: På vegne av en annen privatperson
  - answer: På vegne av virksomhet

- id: KANAL
  type: RADIO
  answers:
  - answer: Serviceklageskjema på nav.no
  - answer: Digital kanal på NAV.no
  - answer: Annen skriftlig kanal fra bruker
  - answer: Muntlig fra bruker
  - answer: Annet

- id: PAAKLAGET_ENHET_ER_BEHANDLENDE
  type: RADIO
  answers:
  - answer: Ja
  - answer: Nei

- id: ENHETSNUMMER_PAAKLAGET
  type: INPUT

- id: ENHETSNUMMER_BEHANDLENDE
  type: INPUT

- id: GJELDER
  type: RADIO
  answers:
  - answer: Gjelder en ytelse eller tjeneste
  - answer: Gjelder flere ting eller sammensatt situasjon

- id: YTELSE
  type: SELECT
  answers:
  - answer: AFP - Avtalefestet pensjon
  - answer: Alderspensjon
  - answer: AAP - Arbeidsavklaringspenger
  - answer: Arbeidsmarkedsloven
  - answer: Barnebidragsområdet
  - answer: Barnepensjon
  - answer: Barnetrygd
  - answer: Barns sykdom
  - answer: Bil
  - answer: Dagpenger
  - answer: Eneforsørger
  - answer: Foreldrepenger
  - answer: Gjenlevende ektefelle
  - answer: Grunnstønad/hjelpestønad
  - answer: Hjelpemidler
  - answer: Kontantstøtte
  - answer: Medlemskap
  - answer: Supplerende stønad
  - answer: Sykepenger
  - answer: Uførepensjon
  - answer: Yrkesskade/yrkessykdom
  - answer: Annet
  - answer: Uspesifisert

- id: TEMA
  type: RADIO
  answers:
  - answer: Vente på NAV
    questions:
    - id: VENTE
      type: RADIO
      answers:
      - answer: Saksbehandlingstid
      - answer: Svartid innsyn
      - answer: Svartid telefon
      - answer: Ventetid kontakt bruker
      - answer: Svartid/ventetid i andre tilfeller
  - answer: Tilgjengelighet
    questions:
    - id: TILGJENGELIGHET
      type: RADIO
      answers:
      - answer: Mulighet til kontakt i dagens kanaler
      - answer: Nedetid i NAVs løsninger
      - answer: Kanal mangler
  - answer: Informasjon
    questions:
    - id: INFORMASJON
      type: RADIO
      answers:
      - answer: Muntlig over telefonen
      - answer: Muntlig ved oppmøte/møte
      - answer: På nav.no /andre brukerflater i NAV
      - answer: I brev
  - answer: Funksjonalitet i NAVs løsninger
  - answer: Veiledning og oppfølging mot arbeid
    questions:
    - id: VEILEDNING
      type: RADIO
      answers:
      - answer: Muntlig over telefon
      - answer: Muntlig ved oppmøte/møte
      - answer: På nav.no/andre brukerflater i NAV
  - answer: NAV-ansattes oppførsel
  - answer: Annet
    questions:
    - id: TEMA_SPESIFISER
      type: INPUT

- id: UTFALL
  type: RADIO
  answers:
  - answer: a) Regler/rutiner/frister er fulgt - NAV har ivaretatt bruker godt
  - answer: b) Regler/rutiner/frister er fulgt men NAV burde ivaretatt bruker bedre
  - answer: c) Regler/rutiner/frister er brutt - NAV burde ivaretatt bruker bedre
    questions:
    - id: AARSAK
      type: TEXT
    - id: TILTAK
      type: TEXT
  - answer: d) Prøvd, men ikke klart å finne ut hva som har skjedd

- id: SVARMETODE
  type: RADIO
  answers:
  - answer: Møte
  - answer: Telefon
  - answer: Modia
  - answer: Manuell post (brev)
  - answer: E-post
  - answer: Svar ikke nødvendig
    questions:
    - id: SVAR_IKKE_NOEDVENDIG
      type: RADIO
      answers:
      - answer: Bruker ikke bedt om svar
      - answer: Annet
        questions:
        - id: SVARMETODE_SPESIFISER
          type: TEXT