name: Build-Deploy-Main-Pipelines
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/workflows/preprod-pipeline.yml'
      - '.github/workflows/manual-deployment.yml'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/workflows/preprod-pipeline.yml'
      - '.github/workflows/manual-deployment.yml'

jobs:
  bygg-app-main:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Define build environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "IMAGE_REGISTRY=ghcr.io/$(echo ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
          echo "IMAGE_NAME=$(echo ${GITHUB_REPOSITORY##/*})" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$(echo ${GITHUB_WORKFLOW})-$(echo ${GITHUB_SHA})" >> $GITHUB_ENV
      - name: Read/save .m2 cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: Set up Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.21.3'
      - name: Build with maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn install --file pom.xml
      - name: Create Docker tag
        env:
          NAME: tilbakemeldingsmottak-api
        run: |
          echo "ghcr.io"/"$GITHUB_REPOSITORY"/"$NAME" > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
      - name: Build docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: Login and push docker image
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin https://ghcr.io
          docker push $(cat .docker_image):$(cat .docker_tag)
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pass tag file to next job.
        uses: actions/upload-artifact@v1
        with:
          name: docker_tag
          path: .docker_tag


  deploy-main:
    name: Deploy to main
    needs: [bygg-app-main]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download tag file
        uses: actions/download-artifact@v1
        with:
          name: docker_tag
      - name: Unpack
        run: |
          cp docker_tag/.docker_tag .
          TAG=$(cat .docker_tag)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin ghcr.io
      - name: Deploy
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yml
          VARS: .nais/p-config.json
          DRY_RUN: false
          IMAGE: ghcr.io/${{ github.repository }}/tilbakemeldingsmottak-api:${{env.TAG}}

  deploy-alerts-prod:
    needs: deploy-prod
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yml
          VARS: .nais/prod-alert.json
