name: Manually triggered deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'preprod'
        type: choice
        options:
          - none
          - preprod
          - prod
env:
  docker_image: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - uses: actions/setup-java@v3
      with:
          distrubution: 'temurin'
          java-version: '17'
          cache: 'maven'
    - name: Set up Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.14.2'

    - name: Set timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Oslo"
    - name: Build with maven
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn install --file pom.xml
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.docker_image }}

  deploy-preprod:
    needs: build-and-push
    if: github.event.inputs.environment == 'preprod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais.yml
          VARS: .nais/preprod-config.json
          VAR: image=${{ env.docker_image }}
          DRY_RUN: false
  deploy-prod:
    needs: build-and-push
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/nais.yml
          VAR: image=${{ env.docker_image }}
          DRY_RUN: false


