name: Manually triggered deployment
run-name: Manual ${{ github.event.inputs.environment }} deploy of branch ${{ github.head_ref || github.ref_name }}
permissions:
  contents: "read"
  id-token: "write"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'preprod-q2'
        type: choice
        options:
          - none
          - preprod
          - preprod-q2
          - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Oslo"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Maven build
        env:
          GITHUB_NAV_TOKEN: ${{ secrets.READER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          mvn clean package --settings maven-settings.xml

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamserviceklage
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: ${{ github.event.inputs.environment }}
          byosbom: target/classes/META-INF/sbom/application.cdx.json
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-preprod:
    needs: [build-and-push]
    if: github.event.inputs.environment == 'preprod'
    name: Deploy to preprod-q1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml
          VARS: .nais/preprod-config.json
          VAR: image=${{needs.build-and-push.outputs.image}}
          DRY_RUN: false


  deploy-preprod-q2:
    needs: [build-and-push]
    if: github.event.inputs.environment == 'preprod-q2'
    name: Deploy to preprod-q2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml
          VARS: .nais/preprod-config-q2.json
          VAR: image=${{needs.build-and-push.outputs.image}}
          DRY_RUN: false

  deploy-prod:
    needs: [build-and-push]
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yml
          VAR: image=${{needs.build-and-push.outputs.image}}
          VARS: .nais/p-config.json
          DRY_RUN: false

  deploy-alerts-preprod:
    needs: [deploy-preprod, deploy-preprod-q2]
    if: ${{ always() && (needs.deploy-preprod.result == 'success' || needs.deploy-preprod-q2.result == 'success') }}
    name: Deploy alerts to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yml
          VARS: .nais/preprod-alert.json

  deploy-alerts-prod:
    if: github.event.inputs.environment == 'prod'
    needs: [deploy-prod]
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yml
          VARS: .nais/prod-alert.json
